language: c

dist: bionic

arch:
    - amd64
    - arm64

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - libsdl2-dev
            - libsdl2-mixer-dev
            - python3-pil

git:
    depth: 1

script:
    - bin/faur-new test
    - make FAUR_PATH=../../.. -C test/build/make -j8
